local parse = require("glinter.parse")

describe("glinter.parse", function()
  it("parses a plain type and subject", function()
    local commit = parse.parse("feat: add parser")
    assert.is_true(commit.valid_header)
    assert.equal("feat", commit.type)
    assert.is_nil(commit.scope)
    assert.is_false(commit.breaking)
    assert.equal("add parser", commit.subject)
    assert.is_true(commit.space_after_colon)
  end)

  it("parses a scoped breaking change", function()
    local commit = parse.parse("feat(cli)!: add hook install")
    assert.equal("feat", commit.type)
    assert.equal("cli", commit.scope)
    assert.is_true(commit.breaking)
    assert.equal("add hook install", commit.subject)
  end)

  it("splits body after a blank line", function()
    local commit = parse.parse("fix: handle empty input\n\nUsers could crash the CLI.")
    assert.equal("fix: handle empty input", commit.header)
    assert.equal("Users could crash the CLI.", commit.body)
    assert.is_true(commit.blank_after_header)
  end)

  it("does not treat a missing blank line as a valid body separator", function()
    local commit = parse.parse("fix: handle empty input\nUsers could crash the CLI.")
    assert.equal("Users could crash the CLI.", commit.body)
    assert.is_false(commit.blank_after_header)
  end)

  it("marks a free-form header as invalid", function()
    local commit = parse.parse("WIP")
    assert.is_false(commit.valid_header)
  end)

  it("ignores merge and version commits", function()
    assert.is_true(parse.is_ignored("Merge branch 'main' into feature"))
    assert.is_true(parse.is_ignored("Revert \"feat: add parser\""))
    assert.is_true(parse.is_ignored("v1.2.3"))
    assert.is_false(parse.is_ignored("feat: add parser"))
  end)
end)
